### ISSUE TITLE
[help wanted] 加一个资源没有被引用的功能

### ISSUE THREAD

**Issue by azhansy** [YK-Unit/r_dart_library#3]
这个库非常棒。
使用这个库的其中一个目标是为了管理好资源的使用情况，
如果已经被废弃的图片资源，我希望能够检索出来。
这样我能够清理掉不用的资源。

**Comment by YK-Unit** [comment]
这个特性我们会进行考虑。然后这个特性实际应该是一个工具特性，所以这个issue适合转移到我们的[Flr](https://github.com/Fly-Mix/flr-cli)这个系列工具上进行后续讨论。
